<?php
/**
 * @file nnphi_training_submit.module
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function nnphi_training_submit_form_webform_submission_submit_a_training_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form["elements"]["nominated_training_information"]["producer"]['#after_build'][] = 'nnphi_training_submit_producer_after_build';
}

/**
 * Producer field #after_build callback.
 */
function nnphi_training_submit_producer_after_build($element) {
  // This gets called twice, and the second call breaks.
  if (isset($element['radios']['other'])) {
    return $element;
  }
  // Re-order the options and place a textfield in the middle.
  $element['radios']["I don't know"]['#weight'] = 9999;
  $element['radios']['other'] = $element['other'];
  $element['radios']['other']['#weight'] = 15;
  $element['other']['#access'] = FALSE;
  return $element;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function nnphi_training_submit_webform_submission_presave(WebformSubmissionInterface $submission) {
  // Qualtrics keeps the "other" input a secondary field.
  // If the user has selected that, move the submitted info
  // into a second field and reset the producer field.
  $producer_options = [
    "I Don't Know",
    'I am the the training producer and the right contact',
    'I am listing contact info of the training producer',
  ];
  $producer_submission = $submission->getElementData('producer');
  if (!in_array($producer_submission, $producer_options)) {
    $submission->setElementData('producer_contact', $producer_submission);
    $submission->setElementData('producer', 'I am listing contact info of the training producer');
  }
}