<?php

/**
 * @file
 * Contains nnphi_general.module.
 */

use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use \Drupal\block_content\BlockContentInterface;
use \Drupal\Component\Utility\Html;
use \Drupal\panels\Plugin\DisplayVariant\PanelsDisplayVariant;
use \Drupal\Core\Render\Element\StatusMessages;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function nnphi_general_block_content_view(array &$build, BlockContentInterface $block, EntityViewDisplayInterface $display, $view_mode) {

  // Add class to link block if boolean is checked to make button outline
  if ($block->bundle() === 'link_block') {
    
    // Add block class here instead of in template since we're adding classes anyway
    $build['#attributes']['class'][] = 'link-block';

    $block_outline_field = $block->get('field_link_block_outline_btn');
    if(!$block_outline_field->isEmpty()) {
      $value = $block_outline_field->getValue();
      if($value[0]['value'] === '1') {
        $build['#attributes']['class'][] = 'link-block-outline';
      }
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 * @param array $suggestions
 * @param array $variables
 */
function nnphi_general_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  // Block suggestions for custom block bundles.
  if (isset($variables['elements']['content']['#block_content'])) {
    array_splice($suggestions, 1, 0, 'block__' . $variables['elements']['content']['#block_content']->bundle());
  }
}

/**
 * Implements hook_preprocess_html().
 * @param $variables
 */
function nnphi_general_preprocess_html(&$variables) {

  // Use route to create an additional page class so that we can target specific
  // pages, e.g., page-user-register
  $route = \Drupal::routeMatch()->getRouteName();
  $variables['page_class'] = HTML::cleanCssIdentifier('page-' . $route, ['.' => '-']);


  // Set maintenance page title
  $maintenance_mode = \Drupal::state()->get('system.maintenance_mode');
  if (!empty($maintenance_mode)) {
    // Only set page title on maintenance page
    // so that admin pages keep normal titles
    if(isset($variables['page']['#theme']) && $variables['page']['#theme'] === 'maintenance_page') {
      $variables['head_title']['title'] = t('Get Notified');
    }
  }
}

/**
 * Implements hook_panels_ipe_blocks_alter().
 */
function nnphi_general_panels_ipe_blocks_alter(array &$blocks = [], PanelsDisplayVariant $panels_display) {
  if ($panels_display->getConfiguration()['storage_id'] !== 'homepage-panels_variant-0') {
    return;
  }
  $providers = [
    'nnphi_training',
    'block_content',
  ];
  foreach ($blocks as $delta => $block) {
    if (!in_array($block['provider'], $providers) ) {
      unset($blocks[$delta]);
    }
  }
}

