<?php
/**
 * @file nnphi_training_track.module
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function nnphi_training_track_node_view_alter(array &$build, NodeInterface $node, EntityViewDisplayInterface $display) {
  if ($node->getType() !== 'training' && $display->getOriginalMode() === 'full') {
    // Remove the history API from the #attached array for performance.
    if (!empty($build['#attached']['library'])) {
      $key =  array_search('history/mark-as-read', $build['#attached']['library']);
      if ($key !== FALSE) {
        unset($build['#attached']['library'][$key]);
      }
    }
  }
}
