name: nnphi
recipe: pantheon
config:
  framework: drupal8
  site: nnphi
  id: 74ca8106-d163-40b3-b7ce-d7d82d1272d6
  xdebug: true
  web_docroot: true
  drupal: true
  drush: global:8.1.12
  php: '7.1'
proxy:
  mailhog:
    - mail.nnphi.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

tooling:
  deploy:
    service: appserver
    description: Run deploy script
    cmd:
      - php
      - /app/web/private/scripts/deploy.php
