pipelines:
  branches:
    master:
      - step:
          name: Deploy to dev
          deployment: test
          script:
            - echo "Deploying..."
            - echo $PANTHEON_FINGERPRINT >> /root/.ssh/known_hosts
            - git remote add pantheon $PANTHEON_REPO
            - git push pantheon master