<?php

/**
 * @file
 * Contains nnphi_curriculum.module.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function nnphi_curriculum_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();
  if ($node->getType() !== 'curriculum') {
    return;
  }
  // Require the summary field.
  $form['field_training_description']['widget'][0]['summary']['#required'] = TRUE;
  $form['field_training_description']['widget'][0]['summary']['#description'] = t('The summary will be displayed in search results and where this content is referenced.');
  // Remove the JS that hides the summary.
  $attached = array_search('text/drupal.text', $form['field_training_description']['widget'][0]['summary']['#attached']['library']);
  unset($form['field_training_description']['widget'][0]['summary']['#attached']['library'][$attached]);
}

/**
 * Implements hook_entity_extra_field_info().
 */
function nnphi_curriculum_entity_extra_field_info() {
  $extra = [];

  $extra['node']['curriculum']['display']['curriculum_enroll'] = [
    'label' => t('Curriculum enrollment link'),
    'description' => t('Link for user to enroll in a curriculum'),
    'weight' => 10,
    'visible' => FALSE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function nnphi_curriculum_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  if (!$display->getComponent('curriculum_enroll') || $node->getType() !== 'curriculum') {
    return;
  }

  $build['#cache']['contexts'][] = 'user.permissions';
  $build['#attached']['library'][] = 'core/drupal.ajax';

  $build['curriculum_enroll'] = [
    '#lazy_builder' => ['nnphi_curriculum.link_builder:curriculum', [
      $node->id(),
    ]],
    '#create_placeholder' => TRUE,
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function nnphi_curriculum_node_view_alter(array &$build, NodeInterface $node, EntityViewDisplayInterface $display) {
  if ($node->getType() !== 'curriculum' || !$display->getComponent('field_curriculum_trainings')) {
    return;
  }
  foreach (Element::children($build['field_curriculum_trainings']) as $delta) {
    $item = &$build['field_curriculum_trainings'][$delta];
    $item['enrollment_link'] = [
      '#lazy_builder' => ['nnphi_curriculum.link_builder:training', [
        $node->id(),
        $item['#node']->id(),
      ]],
      '#create_placeholder' => TRUE,
    ];
  }
}

/**
 * Implements hook_theme().
 */
function nnphi_curriculum_theme($existing, $type, $theme, $path) {
  return [
    'curriculum_enroll' => [
      'variables' => ['action' => 'enroll', 'attributes' => [], 'title' => ''],
    ],
    'curriculum_training_complete' => [
      'variables' => ['attributes' => [], 'container_attributes' => [], 'title' => ''],
    ],
  ];
}
