<?php

namespace Drupal\nnphi_bookmark\Entity;

use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\EntityChangedTrait;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\user\UserInterface;

/**
 * Defines the Bookmark folder entity.
 *
 * @ingroup nnphi_bookmark
 *
 * @ContentEntityType(
 *   id = "bookmark_folder",
 *   label = @Translation("Bookmark folder"),
 *   handlers = {
 *     "view_builder" = "Drupal\nnphi_bookmark\BookmarkFolderViewBuilder",
 *     "list_builder" = "Drupal\nnphi_bookmark\BookmarkFolderListBuilder",
 *     "views_data" = "Drupal\nnphi_bookmark\Entity\BookmarkFolderViewsData",
 *
 *     "form" = {
 *       "default" = "Drupal\nnphi_bookmark\Form\BookmarkFolderForm",
 *       "add" = "Drupal\nnphi_bookmark\Form\BookmarkFolderForm",
 *       "edit" = "Drupal\nnphi_bookmark\Form\BookmarkFolderForm",
 *       "delete" = "Drupal\nnphi_bookmark\Form\BookmarkFolderDeleteForm",
 *     },
 *     "access" = "Drupal\nnphi_bookmark\BookmarkFolderAccessControlHandler",
 *     "route_provider" = {
 *       "html" = "Drupal\nnphi_bookmark\BookmarkFolderHtmlRouteProvider",
 *     },
 *   },
 *   base_table = "bookmark_folder",
 *   admin_permission = "administer bookmark folder entities",
 *   entity_keys = {
 *     "id" = "id",
 *     "label" = "name",
 *     "uuid" = "uuid",
 *     "uid" = "user_id",
 *   },
 *   links = {
 *     "canonical" = "/user/{user}/bookmarks/{bookmark_folder}",
 *     "add-form" = "/user/{user}/bookmarks/add",
 *     "edit-form" = "/user/{user}/bookmarks/{bookmark_folder}/edit",
 *     "delete-form" = "/user/{user}/bookmarks/{bookmark_folder}/delete",
 *     "collection" = "/user/{user}/bookmarks",
 *   },
 *   field_ui_base_route = "bookmark_folder.settings"
 * )
 */
class BookmarkFolder extends ContentEntityBase implements BookmarkFolderInterface {

  use EntityChangedTrait;

  /**
   * {@inheritdoc}
   */
  public static function preCreate(EntityStorageInterface $storage_controller, array &$values) {
    parent::preCreate($storage_controller, $values);
    $values += [
      'user_id' => \Drupal::currentUser()->id(),
    ];
  }

  public function toUrl($rel = 'canonical', array $options = []) {
    return parent::toUrl($rel, $options); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function getName() {
    return $this->get('name')->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setName($name) {
    $this->set('name', $name);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function getCreatedTime() {
    return $this->get('created')->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setCreatedTime($timestamp) {
    $this->set('created', $timestamp);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function getOwner() {
    return $this->get('user_id')->entity;
  }

  /**
   * {@inheritdoc}
   */
  public function getOwnerId() {
    return $this->get('user_id')->target_id;
  }

  /**
   * {@inheritdoc}
   */
  public function setOwnerId($uid) {
    $this->set('user_id', $uid);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function setOwner(UserInterface $account) {
    $this->set('user_id', $account->id());
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  protected function urlRouteParameters($rel) {
    $params = parent::urlRouteParameters($rel);
    $params['user'] = $this->getOwnerId();
    return $params;
  }

  /**
   * {@inheritdoc}
   */
  public static function baseFieldDefinitions(EntityTypeInterface $entity_type) {
    $fields = parent::baseFieldDefinitions($entity_type);

    $fields['user_id'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Owner'))
      ->setDescription(t('The user ID of user that owns the bookmark folder.'))
      ->setRevisionable(TRUE)
      ->setSetting('target_type', 'user')
      ->setSetting('handler', 'default')
      ->setTranslatable(TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'author',
        'weight' => 0,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 5,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'autocomplete_type' => 'tags',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    $fields['name'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Name'))
      ->setDescription(t('The name of the Bookmark folder.'))
      ->setSettings([
        'max_length' => 50,
        'text_processing' => 0,
      ])
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'string',
        'weight' => -4,
      ])
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'weight' => -4,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    $fields['created'] = BaseFieldDefinition::create('created')
      ->setLabel(t('Created'))
      ->setDescription(t('The time that the entity was created.'));

    $fields['changed'] = BaseFieldDefinition::create('changed')
      ->setLabel(t('Changed'))
      ->setDescription(t('The time that the entity was last edited.'));

    return $fields;
  }

}
