<?php

/**
 * @file
 * Contains nnphi_analytics.module.
 */


use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;


/**
 * Implements hook_form_alter().
 */
function nnphi_analytics_form_alter(&$form, FormStateInterface $form_state, $form_id)
{

  if($form_id === 'micro_assessment_form') {
    $form['#attached']['library'][] = 'nnphi_analytics/quiz-analytics';
  }

  if(isset($form["#webform_id"])) {
    $form['#attached']['library'][] = 'nnphi_analytics/webform-analytics';
  }
}


/**
 * Implements hook_ENTITY_TYPE_view().
 */
function nnphi_analytics_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode)
{

  if($node->getType() !== 'training' || $view_mode !== 'full') {
    return;
  }

  $build['#attached']['library'][] = 'nnphi_analytics/training-analytics';
}



/**
 * Implements hook_preprocess_HOOK().
 */
function nnphi_analytics_preprocess_page(&$variables)
{
  $variables['#attached']['library'][] = 'nnphi_analytics/training-search-analytics';

//  if($variables['is_front'] === TRUE) {
    $variables['#attached']['library'][] = 'nnphi_analytics/personalize-analytics';
//  }
}