id: user_password
label: 'User Password'
password_reset: 0
langcode: en
policy_constraints:
  -
    id: password_length
    character_length: 6
    character_operation: minimum
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: uppercase
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: lowercase
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: numeric
roles:
  authenticated: authenticated
  administrator: administrator
